name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.siren.kingstore.dpdns.org", custom_domain = true },  
  { pattern = "quiz.int.vidio.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "info.microsoft.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "wpforms.com.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "zoom.vibenet.world.siren.kingstore.dpdns.org", custom_domain = true },
  { pattern = "thisiswhyimbroke.com.siren.kingstore.dpdns.org", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "c5fc2c0a68644c459f2c5c42240d1876"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "012de424-bf09-438c-82a2-48e74dfb0e8d"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Kingstore25/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/Kingstore25/Siren/refs/heads/master/web/sub.html"
